In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme(style = 'whitegrid')
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

Duplicate key in file WindowsPath('C:/Users/Hyoungrak Oh/.conda/envs/ETA3.9/lib/site-packages/matplotlib/mpl-data/matplotlibrc'), line 257 ('font.family: sans-serif')
Duplicate key in file WindowsPath('C:/Users/Hyoungrak Oh/.conda/envs/ETA3.9/lib/site-packages/matplotlib/mpl-data/matplotlibrc'), line 406 ('axes.unicode_minus: True  # use Unicode for the minus symbol rather than hyphen.  See')

In [2]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')
target = train['failure']
columns = train.columns

In [59]:
test_id = pd.read_csv('./data/test.csv')
test_id = test_id['id']

In [3]:
data = pd.concat([train.drop(columns = ['failure']), test], ignore_index = True)
data

,id,product_code,loading,attribute_0,attribute_1,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,...,measurement_8,measurement_9,measurement_10,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17
0,0,A,80.10,material_7,material_8,9,5,7,8,4,...,20.155,10.672,15.859,17.594,15.193,15.029,NaN,13.034,14.684,764.100
1,1,A,84.89,material_7,material_8,9,5,14,3,3,...,17.889,12.448,17.947,17.915,11.755,14.732,15.425,14.395,15.631,682.057
2,2,A,82.43,material_7,material_8,9,5,12,1,5,...,18.288,12.715,15.607,NaN,13.798,16.711,18.631,14.094,17.946,663.376
3,3,A,101.07,material_7,material_8,9,5,13,2,6,...,19.060,12.471,16.346,18.377,10.020,15.250,15.562,16.154,17.172,826.282
4,4,A,188.06,material_7,material_8,9,5,9,2,8,...,18.093,10.337,17.082,19.932,12.428,16.182,12.760,13.153,16.412,579.885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47340,47340,I,144.74,material_7,material_5,9,5,0,4,9,...,18.573,11.691,NaN,19.771,11.562,17.246,15.131,15.209,NaN,696.466
47341,47341,I,74.53,material_7,material_5,9,5,4,8,7,...,17.917,10.980,16.027,15.694,13.564,15.494,15.296,13.812,16.501,613.249
47342,47342,I,67.73,material_7,material_5,9,5,10,11,2,...,19.630,10.436,16.137,20.612,11.134,16.519,15.525,14.175,17.728,783.349
47343,47343,I,126.15,material_7,material_5,9,5,8,16,11,...,19.575,12.672,15.422,19.496,9.319,15.817,17.403,16.437,15.179,745.210
47344,47344,I,85.97,material_7,material_5,9,5,0,11,11,...,19.253,9.977,17.270,17.924,13.726,14.605,17.460,16.261,16.482,647.980

In [4]:
data.drop(columns = ['id', 'product_code'], inplace = True)
data

,loading,attribute_0,attribute_1,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,...,measurement_8,measurement_9,measurement_10,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17
0,80.10,material_7,material_8,9,5,7,8,4,18.040,12.518,...,20.155,10.672,15.859,17.594,15.193,15.029,NaN,13.034,14.684,764.100
1,84.89,material_7,material_8,9,5,14,3,3,18.213,11.540,...,17.889,12.448,17.947,17.915,11.755,14.732,15.425,14.395,15.631,682.057
2,82.43,material_7,material_8,9,5,12,1,5,18.057,11.652,...,18.288,12.715,15.607,NaN,13.798,16.711,18.631,14.094,17.946,663.376
3,101.07,material_7,material_8,9,5,13,2,6,17.295,11.188,...,19.060,12.471,16.346,18.377,10.020,15.250,15.562,16.154,17.172,826.282
4,188.06,material_7,material_8,9,5,9,2,8,19.346,12.950,...,18.093,10.337,17.082,19.932,12.428,16.182,12.760,13.153,16.412,579.885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47340,144.74,material_7,material_5,9,5,0,4,9,18.465,12.570,...,18.573,11.691,NaN,19.771,11.562,17.246,15.131,15.209,NaN,696.466
47341,74.53,material_7,material_5,9,5,4,8,7,18.900,9.896,...,17.917,10.980,16.027,15.694,13.564,15.494,15.296,13.812,16.501,613.249
47342,67.73,material_7,material_5,9,5,10,11,2,18.656,NaN,...,19.630,10.436,16.137,20.612,11.134,16.519,15.525,14.175,17.728,783.349
47343,126.15,material_7,material_5,9,5,8,16,11,16.536,11.226,...,19.575,12.672,15.422,19.496,9.319,15.817,17.403,16.437,15.179,745.210
47344,85.97,material_7,material_5,9,5,0,11,11,18.373,11.210,...,19.253,9.977,17.270,17.924,13.726,14.605,17.460,16.261,16.482,647.980

In [5]:
data['material_5'] = 0
data['material_6'] = 0
data['material_7'] = 0
data['material_8'] = 0
data

,loading,attribute_0,attribute_1,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
0,80.10,material_7,material_8,9,5,7,8,4,18.040,12.518,...,15.193,15.029,NaN,13.034,14.684,764.100,0,0,0,0
1,84.89,material_7,material_8,9,5,14,3,3,18.213,11.540,...,11.755,14.732,15.425,14.395,15.631,682.057,0,0,0,0
2,82.43,material_7,material_8,9,5,12,1,5,18.057,11.652,...,13.798,16.711,18.631,14.094,17.946,663.376,0,0,0,0
3,101.07,material_7,material_8,9,5,13,2,6,17.295,11.188,...,10.020,15.250,15.562,16.154,17.172,826.282,0,0,0,0
4,188.06,material_7,material_8,9,5,9,2,8,19.346,12.950,...,12.428,16.182,12.760,13.153,16.412,579.885,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47340,144.74,material_7,material_5,9,5,0,4,9,18.465,12.570,...,11.562,17.246,15.131,15.209,NaN,696.466,0,0,0,0
47341,74.53,material_7,material_5,9,5,4,8,7,18.900,9.896,...,13.564,15.494,15.296,13.812,16.501,613.249,0,0,0,0
47342,67.73,material_7,material_5,9,5,10,11,2,18.656,NaN,...,11.134,16.519,15.525,14.175,17.728,783.349,0,0,0,0
47343,126.15,material_7,material_5,9,5,8,16,11,16.536,11.226,...,9.319,15.817,17.403,16.437,15.179,745.210,0,0,0,0
47344,85.97,material_7,material_5,9,5,0,11,11,18.373,11.210,...,13.726,14.605,17.460,16.261,16.482,647.980,0,0,0,0

In [6]:
for i in range(len(data)):
    if data.loc[i, 'attribute_0'] == 'material_5':
        data.loc[i, 'material_5'] = 1
    elif data.loc[i, 'attribute_0'] == 'material_6':
        data.loc[i, 'material_6'] = 1
    elif data.loc[i, 'attribute_0'] == 'material_7':
        data.loc[i, 'material_7'] = 1
    elif data.loc[i, 'attribute_0'] == 'material_8':
        data.loc[i, 'material_8'] = 1

data

,loading,attribute_0,attribute_1,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
0,80.10,material_7,material_8,9,5,7,8,4,18.040,12.518,...,15.193,15.029,NaN,13.034,14.684,764.100,0,0,1,0
1,84.89,material_7,material_8,9,5,14,3,3,18.213,11.540,...,11.755,14.732,15.425,14.395,15.631,682.057,0,0,1,0
2,82.43,material_7,material_8,9,5,12,1,5,18.057,11.652,...,13.798,16.711,18.631,14.094,17.946,663.376,0,0,1,0
3,101.07,material_7,material_8,9,5,13,2,6,17.295,11.188,...,10.020,15.250,15.562,16.154,17.172,826.282,0,0,1,0
4,188.06,material_7,material_8,9,5,9,2,8,19.346,12.950,...,12.428,16.182,12.760,13.153,16.412,579.885,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47340,144.74,material_7,material_5,9,5,0,4,9,18.465,12.570,...,11.562,17.246,15.131,15.209,NaN,696.466,0,0,1,0
47341,74.53,material_7,material_5,9,5,4,8,7,18.900,9.896,...,13.564,15.494,15.296,13.812,16.501,613.249,0,0,1,0
47342,67.73,material_7,material_5,9,5,10,11,2,18.656,NaN,...,11.134,16.519,15.525,14.175,17.728,783.349,0,0,1,0
47343,126.15,material_7,material_5,9,5,8,16,11,16.536,11.226,...,9.319,15.817,17.403,16.437,15.179,745.210,0,0,1,0
47344,85.97,material_7,material_5,9,5,0,11,11,18.373,11.210,...,13.726,14.605,17.460,16.261,16.482,647.980,0,0,1,0

In [7]:
data.drop(columns = ['attribute_0', 'attribute_1'], inplace = True)

In [8]:
train = data[:len(train)]
test = data[len(train):]
display(train)
test

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
0,80.10,9,5,7,8,4,18.040,12.518,15.748,19.292,...,15.193,15.029,NaN,13.034,14.684,764.100,0,0,1,0
1,84.89,9,5,14,3,3,18.213,11.540,17.717,17.893,...,11.755,14.732,15.425,14.395,15.631,682.057,0,0,1,0
2,82.43,9,5,12,1,5,18.057,11.652,16.738,18.240,...,13.798,16.711,18.631,14.094,17.946,663.376,0,0,1,0
3,101.07,9,5,13,2,6,17.295,11.188,18.576,18.339,...,10.020,15.250,15.562,16.154,17.172,826.282,0,0,1,0
4,188.06,9,5,9,2,8,19.346,12.950,16.990,15.746,...,12.428,16.182,12.760,13.153,16.412,579.885,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,158.95,6,9,6,16,4,16.301,13.259,18.068,15.505,...,10.112,15.795,18.572,16.144,NaN,729.131,0,0,1,0
26566,146.02,6,9,10,12,8,17.543,NaN,17.984,19.078,...,10.234,14.450,14.322,13.146,16.471,853.924,0,0,1,0
26567,115.62,6,9,1,10,1,15.670,11.535,16.778,18.385,...,8.668,15.069,16.599,15.590,14.065,750.364,0,0,1,0
26568,106.38,6,9,2,9,4,18.059,NaN,16.918,18.101,...,14.928,16.273,15.485,13.624,12.865,730.156,0,0,1,0
26569,131.20,6,9,6,19,1,18.034,11.431,16.918,17.129,...,11.006,15.875,13.366,16.527,17.890,602.354,0,0,1,0

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
26570,119.57,6,4,6,9,6,19.305,10.178,17.534,18.168,...,13.772,13.659,16.825,13.742,17.710,634.612,1,0,0,0
26571,113.51,6,4,11,8,0,17.883,11.927,17.228,16.033,...,12.473,17.468,16.708,14.776,14.102,537.037,1,0,0,0
26572,112.16,6,4,8,12,4,18.475,10.481,16.619,18.189,...,10.907,13.363,15.737,17.065,16.021,658.995,1,0,0,0
26573,112.72,6,4,8,11,10,16.518,10.888,15.293,18.592,...,10.933,15.501,15.667,12.620,16.111,594.301,1,0,0,0
26574,208.00,6,4,14,16,8,17.808,12.693,17.678,15.814,...,11.941,16.070,16.183,13.324,17.150,801.044,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47340,144.74,9,5,0,4,9,18.465,12.570,18.146,17.089,...,11.562,17.246,15.131,15.209,NaN,696.466,0,0,1,0
47341,74.53,9,5,4,8,7,18.900,9.896,18.288,NaN,...,13.564,15.494,15.296,13.812,16.501,613.249,0,0,1,0
47342,67.73,9,5,10,11,2,18.656,NaN,18.242,17.910,...,11.134,16.519,15.525,14.175,17.728,783.349,0,0,1,0
47343,126.15,9,5,8,16,11,16.536,11.226,18.144,17.250,...,9.319,15.817,17.403,16.437,15.179,745.210,0,0,1,0
47344,85.97,9,5,0,11,11,18.373,11.210,17.030,18.406,...,13.726,14.605,17.460,16.261,16.482,647.980,0,0,1,0

In [9]:
train = pd.concat([train, target], axis = 1)
train

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8,failure
0,80.10,9,5,7,8,4,18.040,12.518,15.748,19.292,...,15.029,NaN,13.034,14.684,764.100,0,0,1,0,0
1,84.89,9,5,14,3,3,18.213,11.540,17.717,17.893,...,14.732,15.425,14.395,15.631,682.057,0,0,1,0,0
2,82.43,9,5,12,1,5,18.057,11.652,16.738,18.240,...,16.711,18.631,14.094,17.946,663.376,0,0,1,0,0
3,101.07,9,5,13,2,6,17.295,11.188,18.576,18.339,...,15.250,15.562,16.154,17.172,826.282,0,0,1,0,0
4,188.06,9,5,9,2,8,19.346,12.950,16.990,15.746,...,16.182,12.760,13.153,16.412,579.885,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,158.95,6,9,6,16,4,16.301,13.259,18.068,15.505,...,15.795,18.572,16.144,NaN,729.131,0,0,1,0,0
26566,146.02,6,9,10,12,8,17.543,NaN,17.984,19.078,...,14.450,14.322,13.146,16.471,853.924,0,0,1,0,0
26567,115.62,6,9,1,10,1,15.670,11.535,16.778,18.385,...,15.069,16.599,15.590,14.065,750.364,0,0,1,0,0
26568,106.38,6,9,2,9,4,18.059,NaN,16.918,18.101,...,16.273,15.485,13.624,12.865,730.156,0,0,1,0,0
26569,131.20,6,9,6,19,1,18.034,11.431,16.918,17.129,...,15.875,13.366,16.527,17.890,602.354,0,0,1,0,0

In [10]:
train_0 = train[train['failure'] == 0]
train_1 = train[train['failure'] == 1]

In [11]:
temp = train_0.loading.mean()
train_0.loading.fillna(temp, inplace = True)
train_0.loading.mean() - temp

C:\Users\HYOUNG~1\AppData\Local\Temp/ipykernel_9468/443544741.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_0.loading.fillna(temp, inplace = True)

1.8474111129762605e-13

In [12]:
temp = train_1.loading.mean()
train_1.loading.fillna(temp, inplace = True)
train_1.loading.mean() - temp

C:\Users\HYOUNG~1\AppData\Local\Temp/ipykernel_9468/3239273625.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_1.loading.fillna(temp, inplace = True)

5.684341886080802e-14

In [13]:
train = pd.concat([train_0, train_1], ignore_index = True)
train

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8,failure
0,80.10,9,5,7,8,4,18.040,12.518,15.748,19.292,...,15.029,NaN,13.034,14.684,764.100,0,0,1,0,0
1,84.89,9,5,14,3,3,18.213,11.540,17.717,17.893,...,14.732,15.425,14.395,15.631,682.057,0,0,1,0,0
2,82.43,9,5,12,1,5,18.057,11.652,16.738,18.240,...,16.711,18.631,14.094,17.946,663.376,0,0,1,0,0
3,101.07,9,5,13,2,6,17.295,11.188,18.576,18.339,...,15.250,15.562,16.154,17.172,826.282,0,0,1,0,0
4,188.06,9,5,9,2,8,19.346,12.950,16.990,15.746,...,16.182,12.760,13.153,16.412,579.885,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,100.26,6,9,4,19,0,18.271,10.381,17.773,18.459,...,NaN,14.601,14.995,17.420,808.354,0,0,1,0,1
26566,103.60,6,9,1,15,3,15.835,12.629,16.460,17.414,...,16.160,15.490,14.522,17.863,731.105,0,0,1,0,1
26567,121.42,6,9,1,9,6,18.186,10.698,17.157,19.184,...,14.981,13.140,14.845,15.577,795.590,0,0,1,0,1
26568,159.43,6,9,3,13,7,19.029,12.330,17.263,NaN,...,14.607,15.494,15.472,14.185,NaN,0,0,1,0,1
26569,120.73,6,9,2,9,9,19.446,12.548,18.185,NaN,...,15.836,16.181,15.864,18.522,1073.039,0,0,1,0,1

In [14]:
train.isnull().sum()

loading              0
attribute_2          0
attribute_3          0
measurement_0        0
measurement_1        0
measurement_2        0
measurement_3      381
measurement_4      538
measurement_5      676
measurement_6      796
measurement_7      937
measurement_8     1048
measurement_9     1227
measurement_10    1300
measurement_11    1468
measurement_12    1601
measurement_13    1774
measurement_14    1874
measurement_15    2009
measurement_16    2110
measurement_17    2284
material_5           0
material_6           0
material_7           0
material_8           0
failure              0
dtype: int64

In [15]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)

In [16]:
imputed = imputer.fit_transform(train.drop(columns = ['failure']))

In [17]:
train = pd.DataFrame(imputed, columns = train.drop(columns = ['failure']).columns)

In [18]:
train = pd.concat([train, target], axis = 1)
train

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8,failure
0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518,15.748,19.2920,...,15.0290,14.2125,13.034,14.684,764.100,0.0,0.0,1.0,0.0,0
1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540,17.717,17.8930,...,14.7320,15.4250,14.395,15.631,682.057,0.0,0.0,1.0,0.0,0
2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652,16.738,18.2400,...,16.7110,18.6310,14.094,17.946,663.376,0.0,0.0,1.0,0.0,0
3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188,18.576,18.3390,...,15.2500,15.5620,16.154,17.172,826.282,0.0,0.0,1.0,0.0,0
4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950,16.990,15.7460,...,16.1820,12.7600,13.153,16.412,579.885,0.0,0.0,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,100.26,6.0,9.0,4.0,19.0,0.0,18.271,10.381,17.773,18.4590,...,14.9945,14.6010,14.995,17.420,808.354,0.0,0.0,1.0,0.0,0
26566,103.60,6.0,9.0,1.0,15.0,3.0,15.835,12.629,16.460,17.4140,...,16.1600,15.4900,14.522,17.863,731.105,0.0,0.0,1.0,0.0,0
26567,121.42,6.0,9.0,1.0,9.0,6.0,18.186,10.698,17.157,19.1840,...,14.9810,13.1400,14.845,15.577,795.590,0.0,0.0,1.0,0.0,0
26568,159.43,6.0,9.0,3.0,13.0,7.0,19.029,12.330,17.263,17.5785,...,14.6070,15.4940,15.472,14.185,604.887,0.0,0.0,1.0,0.0,0
26569,120.73,6.0,9.0,2.0,9.0,9.0,19.446,12.548,18.185,17.1640,...,15.8360,16.1810,15.864,18.522,1073.039,0.0,0.0,1.0,0.0,0

In [19]:
imputed = imputer.transform(test)

In [22]:
test = pd.DataFrame(imputed)
test.columns = train.drop(columns = ['failure']).columns

In [24]:
test

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
0,119.57,6.0,4.0,6.0,9.0,6.0,19.305,10.178,17.534,18.1680,...,13.772,13.659,16.825,13.742,17.710,634.612,1.0,0.0,0.0,0.0
1,113.51,6.0,4.0,11.0,8.0,0.0,17.883,11.927,17.228,16.0330,...,12.473,17.468,16.708,14.776,14.102,537.037,1.0,0.0,0.0,0.0
2,112.16,6.0,4.0,8.0,12.0,4.0,18.475,10.481,16.619,18.1890,...,10.907,13.363,15.737,17.065,16.021,658.995,1.0,0.0,0.0,0.0
3,112.72,6.0,4.0,8.0,11.0,10.0,16.518,10.888,15.293,18.5920,...,10.933,15.501,15.667,12.620,16.111,594.301,1.0,0.0,0.0,0.0
4,208.00,6.0,4.0,14.0,16.0,8.0,17.808,12.693,17.678,15.8140,...,11.941,16.070,16.183,13.324,17.150,801.044,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570,18.146,17.0890,...,11.562,17.246,15.131,15.209,16.046,696.466,0.0,0.0,1.0,0.0
20771,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896,18.288,19.0215,...,13.564,15.494,15.296,13.812,16.501,613.249,0.0,0.0,1.0,0.0
20772,67.73,9.0,5.0,10.0,11.0,2.0,18.656,12.396,18.242,17.9100,...,11.134,16.519,15.525,14.175,17.728,783.349,0.0,0.0,1.0,0.0
20773,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226,18.144,17.2500,...,9.319,15.817,17.403,16.437,15.179,745.210,0.0,0.0,1.0,0.0
20774,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210,17.030,18.4060,...,13.726,14.605,17.460,16.261,16.482,647.980,0.0,0.0,1.0,0.0

In [25]:
X_train, X_test, y_train, y_test = train_test_split(train.drop(columns = ['failure']), train.failure, random_state = 42)

In [43]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set(style='darkgrid', font_scale=1.4)
import matplotlib.pyplot as plt
%matplotlib inline

from itertools import combinations
import math
import statistics

from scipy import stats
from scipy.stats import pearsonr
from scipy.stats import chi2
from scipy.stats import poisson

import time

from datetime import datetime
import matplotlib.dates as mdates
import plotly.express as px
import lightgbm as lgbm
from termcolor import colored
import itertools
import warnings
warnings.filterwarnings("ignore")

import sklearn
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV, TimeSeriesSplit, GroupKFold, cross_validate
from sklearn.preprocessing import StandardScaler, RobustScaler, PowerTransformer, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.mixture import GaussianMixture, BayesianGaussianMixture

# UMAP
import umap
# import umap.plot

# Models
from sklearn.linear_model import LinearRegression, LogisticRegression, Lasso, Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import early_stopping
from lightgbm import LGBMClassifier, LGBMRegressor

from catboost import CatBoostClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from lightgbm.sklearn import LGBMClassifier
from lightgbm.sklearn import LGBMRegressor

# 상관관계 분석, VIF : 다중공선성 제거
from statsmodels.stats.outliers_influence import variance_inflation_factor

# KFold(CV), partial : optuna를 사용하기 위함
from sklearn.model_selection import KFold
from functools import partial

# hyper-parameter tuning을 위한 라이브러리, optuna
import optuna

# sklearn에서 배웠던 분류 모델들을 불러와봅니다.
from sklearn.linear_model import SGDClassifier      # 1. Linear Classifier
from sklearn.linear_model import LogisticRegression # 2. Logistic Regression
from sklearn.tree import DecisionTreeClassifier     # 3. Decision Tree
from sklearn.ensemble import RandomForestClassifier # 4. Random Forest

# 평가 지표
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [45]:
X = train.drop(columns = ['failure'])
X

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,material_5,material_6,material_7,material_8
0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518,15.748,19.2920,...,15.193,15.0290,14.2125,13.034,14.684,764.100,0.0,0.0,1.0,0.0
1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540,17.717,17.8930,...,11.755,14.7320,15.4250,14.395,15.631,682.057,0.0,0.0,1.0,0.0
2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652,16.738,18.2400,...,13.798,16.7110,18.6310,14.094,17.946,663.376,0.0,0.0,1.0,0.0
3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188,18.576,18.3390,...,10.020,15.2500,15.5620,16.154,17.172,826.282,0.0,0.0,1.0,0.0
4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950,16.990,15.7460,...,12.428,16.1820,12.7600,13.153,16.412,579.885,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,100.26,6.0,9.0,4.0,19.0,0.0,18.271,10.381,17.773,18.4590,...,12.666,14.9945,14.6010,14.995,17.420,808.354,0.0,0.0,1.0,0.0
26566,103.60,6.0,9.0,1.0,15.0,3.0,15.835,12.629,16.460,17.4140,...,12.310,16.1600,15.4900,14.522,17.863,731.105,0.0,0.0,1.0,0.0
26567,121.42,6.0,9.0,1.0,9.0,6.0,18.186,10.698,17.157,19.1840,...,10.795,14.9810,13.1400,14.845,15.577,795.590,0.0,0.0,1.0,0.0
26568,159.43,6.0,9.0,3.0,13.0,7.0,19.029,12.330,17.263,17.5785,...,12.350,14.6070,15.4940,15.472,14.185,604.887,0.0,0.0,1.0,0.0
26569,120.73,6.0,9.0,2.0,9.0,9.0,19.446,12.548,18.185,17.1640,...,10.699,15.8360,16.1810,15.864,18.522,1073.039,0.0,0.0,1.0,0.0

In [46]:
y = train.failure
y

0        0
1        0
2        0
3        0
4        0
        ..
26565    0
26566    0
26567    0
26568    0
26569    0
Name: failure, Length: 26570, dtype: int64

In [47]:
clf = SGDClassifier()
clf2 = LogisticRegression()
clf3 = DecisionTreeClassifier()
clf4 = RandomForestClassifier()
clf5 = LinearRegression()
clf6 = Lasso()
clf7 = Ridge()
clf8 = XGBClassifier()
clf9 = XGBRegressor()
#clf10 = LGBMClassifier()
#clf11 = LGBMRegressor()

clf.fit(X, y)
clf2.fit(X, y)
clf3.fit(X, y)
clf4.fit(X, y)
clf5.fit(X, y)
clf6.fit(X, y)
clf7.fit(X, y)
clf8.fit(X, y)
clf9.fit(X, y)
#clf10.fit(X, y)
#clf11.fit(X, y)

pred = clf.predict(X)
pred2 = clf2.predict(X)
pred3 = clf3.predict(X)
pred4 = clf4.predict(X)
pred5 = clf5.predict(X)
pred6 = clf6.predict(X)
pred7 = clf7.predict(X)
pred8 = clf8.predict(X)
pred9 = clf9.predict(X)
#pred10 = clf.predict(X)
#pred11 = clf.predict(X)

[21:55:51] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [48]:
print("1. SGDClassifier, Accuracy for training : %.4f" % accuracy_score(y, pred))
print("2. LogisticRegression, Accuracy for training : %.4f" % accuracy_score(y, pred2))
print("3. DecisionTreeClassifie, Accuracy for training : %.4f" % accuracy_score(y, pred3))
print("4. RandomForestClassifier, Accuracy for training : %.4f" % accuracy_score(y, pred4))
print("5. LinearRegression, Accuracy for training : %.4f" % accuracy_score(y, pred5))
print("6. Lasso, Accuracy for training : %.4f" % accuracy_score(y, pred6))
print("7. Ridge, Accuracy for training : %.4f" % accuracy_score(y, pred7))
print("8. XGBClassifier, Accuracy for training : %.4f" % accuracy_score(y, pred8))
print("9. XGBRegressor, Accuracy for training : %.4f" % accuracy_score(y, pred9))

1. SGDClassifier, Accuracy for training : 0.2126
2. LogisticRegression, Accuracy for training : 0.7874
3. DecisionTreeClassifie, Accuracy for training : 1.0000
4. RandomForestClassifier, Accuracy for training : 1.0000

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [64]:
pred2 = clf2.predict(test)

In [65]:
pred2 = pd.DataFrame(pred2)
pred2 = pd.concat([test_id, pred2], axis = 1)
pred2.columns = ['id', 'failure']

In [66]:
pred2

          id  failure
0      26570        0
1      26571        0
2      26572        0
3      26573        0
4      26574        0
...      ...      ...
20770  47340        0
20771  47341        0
20772  47342        0
20773  47343        0
20774  47344        0

[20775 rows x 2 columns]

In [69]:
pred2.to_csv('./predict/20220816.csv', index= False)